[[pages]]
name = "Home"
path = "dashboard/app.py"
icon = "🏰"

[[pages]]
name = "Spelers"
path = "dashboard/pages/2_players.py"
icon = "👤"

[[pages]]
name = "Speler detail"
path = "dashboard/pages/3_player_detail.py"
icon = "📊"
is_hidden = true

[[pages]]
name = "Head to Head"
path = "dashboard/pages/4_head_to_head.py"
icon = "⚔️"
is_hidden = true
